INSERT INTO tb_user (name, email, password) VALUES ('Alex', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Maria', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Animação');

INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Frozen', 'Descubra o passado. Enfrente o futuro.', 2019, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/pNbmSYUtMd542OATplZIdtSWKyz.jpg', 'De volta à infância de Elsa e Anna, as duas garotas descobrem uma história do pai, quando ainda era príncipe de Arendelle. Ele conta às meninas a história de uma visita à floresta dos elementos, onde um acontecimento inesperado teria provocado a separação dos habitantes da cidade com os quatro elementos fundamentais: ar, fogo, terra e água. Esta revelação ajudará Elsa a compreender a origem de seus poderes.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Hard Kill', 'Take on a madman. Save the world.', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/86L8wqGMDbwURPni2t7FQ0nDjsH.jpg', 'O trabalho do bilionário CEO de tecnologia Donovan Chalmers (Willis) é tão valioso que ele contrata mercenários para protegê-lo e um grupo terrorista sequestra sua filha apenas para obtê-lo.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Destruição Final', 'O Último Refúgio', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg', 'Quando cientistas descobrem que um cometa atingirá a Terra em poucos dias e provavelmente causará a extinção da humanidade, uma família tenta cruzar o país para chegar a sua única esperança de sobrevivência: um grupo de abrigos subterrâneos em Greenland.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Bob Esponja: O Incrível Resgate', 'Eles já não estão na Fenda do Biquini', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/bt4xA9WZE9P1wiRILRFt0Zh2wmV.jpg', 'Onde está Gary? Segundo Bob Esponja, Gary foi "caracolstrado" pelo temível Rei Poseidon e levado para a cidade perdida de Atlantic City. Junto a Patrick Estrela, ele sai em uma missão de resgate ao querido amigo, e nesta jornada os dois vão conhecer novos personagens e viver inimagináveis aventuras.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Mulan', 'Mulan Live Action', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/qAKvUu2FSaDlnqznY4VOp5PmjIF.jpg', 'Hua Mulan é a espirituosa e determinada filha mais velha de um honrado guerreiro. Quando o Imperador da China emite um decreto que um homem de cada família deve servir no exército imperial, Mulan decide tomar o lugar de seu pai, que está doente. Assumindo a identidade de Hua Jun, ela se disfarça de homem para combater os invasores que estão atacando sua nação, provando-se uma grande guerreira.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Come Play', 'He good at taking friends.', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/5HahZPsGGaDgnFb68J49ZwdwU0b.jpg', 'Oliver é um garoto autista. Desesperado por amigos, encontra um refúgio no seu celular e tablet. Quando uma misteriosa criatura se manifesta usando seus aparelhos, os pais precisam fazer tudo para salvar seu filho dessa ameaça.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Bronx', 'Onde tudo começou', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/gnf4Cb2rms69QbCnGFJyqwBWsxv.jpg', 'Marselha. Tudo começa com a carnificina causada pelos homens do clã Orsoni. Richard Vronski, um policial da brigada anti-gangue com métodos pouco ortodoxos, se vê encarregado da investigação, enfrentando seus rivais, comandados por Costa, major da polícia. Um novo diretor, o comissário Angel Leonetti chega para dominar os cães loucos de sua equipe. Mas todos perceberão rapidamente que não se recebe nada sem sacrifícios ou riscos.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('A Caminho da Lua', 'Believing is Everything', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/htBUhLSS7FfHtydgYxUWjL3J1Q1.jpg', 'Uma garota constrói uma nave espacial e parte rumo ao espaço à procura da deusa da lua.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Batman: Morte em Família', 'The fate of Gotham is in your hands.', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/kU7ZiyeUwcpTkYj3UcxSqGdZmxY.jpg', 'Baseado na HQ “Batman: Morte em Família”, o longa conta a história da relação do Batman com seu pupilo Jason Todd, o segundo Robin. Após a relação entre os dois ficar abalada por conta do comportamento extremo de Jason em suas rondas, o Coringa o mata, levando o Batman ao limite.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Baba Yaga', 'Terror da Floresta Negra', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/4br4B8C0SRIYcKHUgoaOlGo50MU.jpg', 'Uma família se muda recentemente para a nova casa após o nascimento do bebê. Logo, eles contratam uma babá para cuidar da recém-nascida. No entanto, Egor, o filho mais velho, fala sobre o comportamento assustador da mulher, mas seus pais não acreditam nele. Então, um dia, Egor chega em casa e não encontra vestígios da babá e nem da criança. Também se depara com os pais em transe, sem ao menos lembrar que tiveram uma filha.', 2);

INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Filme muito bom!', 2, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Não gostei, muito fraco para terror', 10, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Eu e meu filho gostou muito!', 1, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Chato!', 7, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Show! filme top.', 9, 2);